version: "3.9"
services:
  backend_api:
    build: backend/.
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - api_data:/app/data # Custom volume for web service data
      - ./backend:/app
    restart: always
    networks:
      - app-network

volumes:
  api_data:
    driver: local # Use the local driver for web service data

networks:
  app-network: